// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using Invert.StateMachine;


public class InGameStateMachine : Invert.StateMachine.StateMachine {
    
    private Invert.StateMachine.StateMachineTrigger _GameStart;
    
    private Invert.StateMachine.StateMachineTrigger _GameStop;
    
    private Invert.StateMachine.StateMachineTrigger _PrepareNewGame;
    
    private Ready _Ready;
    
    private Ongoing _Ongoing;
    
    private Stop _Stop;
    
    public InGameStateMachine(uFrame.MVVM.ViewModel vm, string propertyName) : 
            base(vm, propertyName) {
    }
    
    public InGameStateMachine() : 
            base(null, string.Empty) {
    }
    
    public override Invert.StateMachine.State StartState {
        get {
            return this.Ready;
        }
    }
    
    public virtual Invert.StateMachine.StateMachineTrigger GameStart {
        get {
            if (this._GameStart == null) {
                this._GameStart = new StateMachineTrigger(this , "GameStart");
            }
            return _GameStart;
        }
        set {
            _GameStart = value;
        }
    }
    
    public virtual Invert.StateMachine.StateMachineTrigger GameStop {
        get {
            if (this._GameStop == null) {
                this._GameStop = new StateMachineTrigger(this , "GameStop");
            }
            return _GameStop;
        }
        set {
            _GameStop = value;
        }
    }
    
    public virtual Invert.StateMachine.StateMachineTrigger PrepareNewGame {
        get {
            if (this._PrepareNewGame == null) {
                this._PrepareNewGame = new StateMachineTrigger(this , "PrepareNewGame");
            }
            return _PrepareNewGame;
        }
        set {
            _PrepareNewGame = value;
        }
    }
    
    public virtual Ready Ready {
        get {
            if (this._Ready == null) {
                this._Ready = new Ready();
            }
            return _Ready;
        }
        set {
            _Ready = value;
        }
    }
    
    public virtual Ongoing Ongoing {
        get {
            if (this._Ongoing == null) {
                this._Ongoing = new Ongoing();
            }
            return _Ongoing;
        }
        set {
            _Ongoing = value;
        }
    }
    
    public virtual Stop Stop {
        get {
            if (this._Stop == null) {
                this._Stop = new Stop();
            }
            return _Stop;
        }
        set {
            _Stop = value;
        }
    }
    
    public override void Compose(System.Collections.Generic.List<Invert.StateMachine.State> states) {
        base.Compose(states);
        Ready.GameStart = new StateTransition("GameStart", Ready, Ongoing);
        Transitions.Add(Ready.GameStart);
        Ready.AddTrigger(GameStart, Ready.GameStart);
        Ready.StateMachine = this;
        states.Add(Ready);
        Ongoing.GameStop = new StateTransition("GameStop", Ongoing, Stop);
        Transitions.Add(Ongoing.GameStop);
        Ongoing.AddTrigger(GameStop, Ongoing.GameStop);
        Ongoing.StateMachine = this;
        states.Add(Ongoing);
        Stop.PrepareNewGame = new StateTransition("PrepareNewGame", Stop, Ready);
        Transitions.Add(Stop.PrepareNewGame);
        Stop.AddTrigger(PrepareNewGame, Stop.PrepareNewGame);
        Stop.StateMachine = this;
        states.Add(Stop);
    }
}

public class Ready : Invert.StateMachine.State {
    
    private Invert.StateMachine.StateTransition _GameStart;
    
    public Invert.StateMachine.StateTransition GameStart {
        get {
            return _GameStart;
        }
        set {
            _GameStart = value;
        }
    }
    
    public override string Name {
        get {
            return "Ready";
        }
    }
    
    public virtual void GameStartTransition() {
        this.Transition(this.GameStart);
    }
}

public class Ongoing : Invert.StateMachine.State {
    
    private Invert.StateMachine.StateTransition _GameStop;
    
    public Invert.StateMachine.StateTransition GameStop {
        get {
            return _GameStop;
        }
        set {
            _GameStop = value;
        }
    }
    
    public override string Name {
        get {
            return "Ongoing";
        }
    }
    
    public virtual void GameStopTransition() {
        this.Transition(this.GameStop);
    }
}

public class Stop : Invert.StateMachine.State {
    
    private Invert.StateMachine.StateTransition _PrepareNewGame;
    
    public Invert.StateMachine.StateTransition PrepareNewGame {
        get {
            return _PrepareNewGame;
        }
        set {
            _PrepareNewGame = value;
        }
    }
    
    public override string Name {
        get {
            return "Stop";
        }
    }
    
    public virtual void PrepareNewGameTransition() {
        this.Transition(this.PrepareNewGame);
    }
}
