// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using uFrame.IOC;
using uFrame.Kernel;
using uFrame.MVVM;


public class InGameSysLoaderBase : uFrame.Kernel.SystemLoader {
    
    private CharacterController _CharacterController;
    
    private InGameRootController _InGameRootController;
    
    [uFrame.IOC.InjectAttribute()]
    public virtual CharacterController CharacterController {
        get {
            if (_CharacterController==null) {
                _CharacterController = Container.CreateInstance(typeof(CharacterController)) as CharacterController;;
            }
            return _CharacterController;
        }
        set {
            _CharacterController = value;
        }
    }
    
    [uFrame.IOC.InjectAttribute()]
    public virtual InGameRootController InGameRootController {
        get {
            if (_InGameRootController==null) {
                _InGameRootController = Container.CreateInstance(typeof(InGameRootController)) as InGameRootController;;
            }
            return _InGameRootController;
        }
        set {
            _InGameRootController = value;
        }
    }
    
    public override void Load() {
        Container.RegisterViewModelManager<CharacterViewModel>(new ViewModelManager<CharacterViewModel>());
        Container.RegisterController<CharacterController>(CharacterController);
        Container.RegisterViewModelManager<InGameRootViewModel>(new ViewModelManager<InGameRootViewModel>());
        Container.RegisterController<InGameRootController>(InGameRootController);
    }
}
