// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using uFrame.IOC;
using uFrame.Kernel;
using uFrame.MVVM;
using uFrame.MVVM.Bindings;
using uFrame.Serialization;
using UnityEngine;
using UniRx;


public partial class AnimalViewModelBase : uFrame.MVVM.ViewModel {
    
    private P<AnimalType> _AnimalTypeProperty;
    
    public AnimalViewModelBase(uFrame.Kernel.IEventAggregator aggregator) : 
            base(aggregator) {
    }
    
    public virtual P<AnimalType> AnimalTypeProperty {
        get {
            return _AnimalTypeProperty;
        }
        set {
            _AnimalTypeProperty = value;
        }
    }
    
    public virtual AnimalType AnimalType {
        get {
            return AnimalTypeProperty.Value;
        }
        set {
            AnimalTypeProperty.Value = value;
        }
    }
    
    public override void Bind() {
        base.Bind();
        _AnimalTypeProperty = new P<AnimalType>(this, "AnimalType");
    }
    
    public override void Read(ISerializerStream stream) {
        base.Read(stream);
        this.AnimalType = (AnimalType)stream.DeserializeInt("AnimalType");;
    }
    
    public override void Write(ISerializerStream stream) {
        base.Write(stream);
        stream.SerializeInt("AnimalType", (int)this.AnimalType);;
    }
    
    protected override void FillCommands(System.Collections.Generic.List<uFrame.MVVM.ViewModelCommandInfo> list) {
        base.FillCommands(list);
    }
    
    protected override void FillProperties(System.Collections.Generic.List<uFrame.MVVM.ViewModelPropertyInfo> list) {
        base.FillProperties(list);
        // PropertiesChildItem
        list.Add(new ViewModelPropertyInfo(_AnimalTypeProperty, false, false, true, false));
    }
}

public partial class AnimalViewModel {
    
    public AnimalViewModel(uFrame.Kernel.IEventAggregator aggregator) : 
            base(aggregator) {
    }
}

public partial class InGameRootViewModelBase : uFrame.MVVM.ViewModel {
    
    private InGameStateMachine _InGameStateProperty;
    
    private Signal<AddAnimalCommand> _AddAnimal;
    
    public InGameRootViewModelBase(uFrame.Kernel.IEventAggregator aggregator) : 
            base(aggregator) {
    }
    
    public virtual InGameStateMachine InGameStateProperty {
        get {
            return _InGameStateProperty;
        }
        set {
            _InGameStateProperty = value;
        }
    }
    
    public virtual Invert.StateMachine.State InGameState {
        get {
            return InGameStateProperty.Value;
        }
        set {
            InGameStateProperty.Value = value;
        }
    }
    
    public virtual Signal<AddAnimalCommand> AddAnimal {
        get {
            return _AddAnimal;
        }
        set {
            _AddAnimal = value;
        }
    }
    
    public override void Bind() {
        base.Bind();
        this.AddAnimal = new Signal<AddAnimalCommand>(this);
        _InGameStateProperty = new InGameStateMachine(this, "InGameState");
    }
    
    public override void Read(ISerializerStream stream) {
        base.Read(stream);
        this._InGameStateProperty.SetState(stream.DeserializeString("InGameState"));
    }
    
    public override void Write(ISerializerStream stream) {
        base.Write(stream);
        stream.SerializeString("InGameState", this.InGameState.Name);;
    }
    
    protected override void FillCommands(System.Collections.Generic.List<uFrame.MVVM.ViewModelCommandInfo> list) {
        base.FillCommands(list);
        list.Add(new ViewModelCommandInfo("AddAnimal", AddAnimal) { ParameterType = typeof(void) });
    }
    
    protected override void FillProperties(System.Collections.Generic.List<uFrame.MVVM.ViewModelPropertyInfo> list) {
        base.FillProperties(list);
        // PropertiesChildItem
        list.Add(new ViewModelPropertyInfo(_InGameStateProperty, false, false, false, false));
    }
}

public partial class InGameRootViewModel {
    
    public InGameRootViewModel(uFrame.Kernel.IEventAggregator aggregator) : 
            base(aggregator) {
    }
}

public partial class BlueBirdAnimalViewModelBase : AnimalViewModel {
    
    public BlueBirdAnimalViewModelBase(uFrame.Kernel.IEventAggregator aggregator) : 
            base(aggregator) {
    }
    
    public override void Bind() {
        base.Bind();
    }
    
    public override void Read(ISerializerStream stream) {
        base.Read(stream);
    }
    
    public override void Write(ISerializerStream stream) {
        base.Write(stream);
    }
    
    protected override void FillCommands(System.Collections.Generic.List<uFrame.MVVM.ViewModelCommandInfo> list) {
        base.FillCommands(list);
    }
    
    protected override void FillProperties(System.Collections.Generic.List<uFrame.MVVM.ViewModelPropertyInfo> list) {
        base.FillProperties(list);
    }
}

public partial class BlueBirdAnimalViewModel {
    
    public BlueBirdAnimalViewModel(uFrame.Kernel.IEventAggregator aggregator) : 
            base(aggregator) {
    }
}

public partial class CoffeeCowAnimalViewModelBase : AnimalViewModel {
    
    public CoffeeCowAnimalViewModelBase(uFrame.Kernel.IEventAggregator aggregator) : 
            base(aggregator) {
    }
    
    public override void Bind() {
        base.Bind();
    }
    
    public override void Read(ISerializerStream stream) {
        base.Read(stream);
    }
    
    public override void Write(ISerializerStream stream) {
        base.Write(stream);
    }
    
    protected override void FillCommands(System.Collections.Generic.List<uFrame.MVVM.ViewModelCommandInfo> list) {
        base.FillCommands(list);
    }
    
    protected override void FillProperties(System.Collections.Generic.List<uFrame.MVVM.ViewModelPropertyInfo> list) {
        base.FillProperties(list);
    }
}

public partial class CoffeeCowAnimalViewModel {
    
    public CoffeeCowAnimalViewModel(uFrame.Kernel.IEventAggregator aggregator) : 
            base(aggregator) {
    }
}

public partial class GreenFrogAnimalViewModelBase : AnimalViewModel {
    
    public GreenFrogAnimalViewModelBase(uFrame.Kernel.IEventAggregator aggregator) : 
            base(aggregator) {
    }
    
    public override void Bind() {
        base.Bind();
    }
    
    public override void Read(ISerializerStream stream) {
        base.Read(stream);
    }
    
    public override void Write(ISerializerStream stream) {
        base.Write(stream);
    }
    
    protected override void FillCommands(System.Collections.Generic.List<uFrame.MVVM.ViewModelCommandInfo> list) {
        base.FillCommands(list);
    }
    
    protected override void FillProperties(System.Collections.Generic.List<uFrame.MVVM.ViewModelPropertyInfo> list) {
        base.FillProperties(list);
    }
}

public partial class GreenFrogAnimalViewModel {
    
    public GreenFrogAnimalViewModel(uFrame.Kernel.IEventAggregator aggregator) : 
            base(aggregator) {
    }
}
