// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using uFrame.IOC;
using uFrame.Kernel;
using uFrame.MVVM;
using uFrame.MVVM.Bindings;
using uFrame.Serialization;
using UnityEngine;
using UniRx;


public partial class AnimalViewModelBase : uFrame.MVVM.ViewModel {
    
    private P<AnimalType> _AnimalTypeProperty;
    
    private P<Int32> _sameCountProperty;
    
    private P<Loc> _LocProperty;
    
    private Signal<TappedCommand> _Tapped;
    
    public AnimalViewModelBase(uFrame.Kernel.IEventAggregator aggregator) : 
            base(aggregator) {
    }
    
    public virtual P<AnimalType> AnimalTypeProperty {
        get {
            return _AnimalTypeProperty;
        }
        set {
            _AnimalTypeProperty = value;
        }
    }
    
    public virtual P<Int32> sameCountProperty {
        get {
            return _sameCountProperty;
        }
        set {
            _sameCountProperty = value;
        }
    }
    
    public virtual P<Loc> LocProperty {
        get {
            return _LocProperty;
        }
        set {
            _LocProperty = value;
        }
    }
    
    public virtual AnimalType AnimalType {
        get {
            return AnimalTypeProperty.Value;
        }
        set {
            AnimalTypeProperty.Value = value;
        }
    }
    
    public virtual Int32 sameCount {
        get {
            return sameCountProperty.Value;
        }
        set {
            sameCountProperty.Value = value;
        }
    }
    
    public virtual Loc Loc {
        get {
            return LocProperty.Value;
        }
        set {
            LocProperty.Value = value;
        }
    }
    
    public virtual Signal<TappedCommand> Tapped {
        get {
            return _Tapped;
        }
        set {
            _Tapped = value;
        }
    }
    
    public override void Bind() {
        base.Bind();
        this.Tapped = new Signal<TappedCommand>(this);
        _AnimalTypeProperty = new P<AnimalType>(this, "AnimalType");
        _sameCountProperty = new P<Int32>(this, "sameCount");
        _LocProperty = new P<Loc>(this, "Loc");
    }
    
    public override void Read(ISerializerStream stream) {
        base.Read(stream);
        this.AnimalType = (AnimalType)stream.DeserializeInt("AnimalType");;
        this.sameCount = stream.DeserializeInt("sameCount");;
    }
    
    public override void Write(ISerializerStream stream) {
        base.Write(stream);
        stream.SerializeInt("AnimalType", (int)this.AnimalType);;
        stream.SerializeInt("sameCount", this.sameCount);
    }
    
    protected override void FillCommands(System.Collections.Generic.List<uFrame.MVVM.ViewModelCommandInfo> list) {
        base.FillCommands(list);
        list.Add(new ViewModelCommandInfo("Tapped", Tapped) { ParameterType = typeof(void) });
    }
    
    protected override void FillProperties(System.Collections.Generic.List<uFrame.MVVM.ViewModelPropertyInfo> list) {
        base.FillProperties(list);
        // PropertiesChildItem
        list.Add(new ViewModelPropertyInfo(_AnimalTypeProperty, false, false, true, false));
        // PropertiesChildItem
        list.Add(new ViewModelPropertyInfo(_sameCountProperty, false, false, false, false));
        // PropertiesChildItem
        list.Add(new ViewModelPropertyInfo(_LocProperty, false, false, false, false));
    }
}

public partial class AnimalViewModel {
    
    public AnimalViewModel(uFrame.Kernel.IEventAggregator aggregator) : 
            base(aggregator) {
    }
}

public partial class InGameRootViewModelBase : uFrame.MVVM.ViewModel {
    
    private InGameStateMachine _InGameStateProperty;
    
    private ModelCollection<AnimalViewModel> _AnimalCollections;
    
    private Signal<CreateAnimalCommand> _CreateAnimal;
    
    public InGameRootViewModelBase(uFrame.Kernel.IEventAggregator aggregator) : 
            base(aggregator) {
    }
    
    public virtual InGameStateMachine InGameStateProperty {
        get {
            return _InGameStateProperty;
        }
        set {
            _InGameStateProperty = value;
        }
    }
    
    public virtual Invert.StateMachine.State InGameState {
        get {
            return InGameStateProperty.Value;
        }
        set {
            InGameStateProperty.Value = value;
        }
    }
    
    public virtual ModelCollection<AnimalViewModel> AnimalCollections {
        get {
            return _AnimalCollections;
        }
        set {
            _AnimalCollections = value;
        }
    }
    
    public virtual Signal<CreateAnimalCommand> CreateAnimal {
        get {
            return _CreateAnimal;
        }
        set {
            _CreateAnimal = value;
        }
    }
    
    public override void Bind() {
        base.Bind();
        this.CreateAnimal = new Signal<CreateAnimalCommand>(this);
        _AnimalCollections = new ModelCollection<AnimalViewModel>(this, "AnimalCollections");
        _InGameStateProperty = new InGameStateMachine(this, "InGameState");
    }
    
    public override void Read(ISerializerStream stream) {
        base.Read(stream);
        this._InGameStateProperty.SetState(stream.DeserializeString("InGameState"));
        if (stream.DeepSerialize) {
            this.AnimalCollections.Clear();
            this.AnimalCollections.AddRange(stream.DeserializeObjectArray<AnimalViewModel>("AnimalCollections"));
        }
    }
    
    public override void Write(ISerializerStream stream) {
        base.Write(stream);
        stream.SerializeString("InGameState", this.InGameState.Name);;
        if (stream.DeepSerialize) stream.SerializeArray("AnimalCollections", this.AnimalCollections);
    }
    
    protected override void FillCommands(System.Collections.Generic.List<uFrame.MVVM.ViewModelCommandInfo> list) {
        base.FillCommands(list);
        list.Add(new ViewModelCommandInfo("CreateAnimal", CreateAnimal) { ParameterType = typeof(AnimalProp) });
    }
    
    protected override void FillProperties(System.Collections.Generic.List<uFrame.MVVM.ViewModelPropertyInfo> list) {
        base.FillProperties(list);
        // PropertiesChildItem
        list.Add(new ViewModelPropertyInfo(_InGameStateProperty, false, false, false, false));
        list.Add(new ViewModelPropertyInfo(_AnimalCollections, true, true, false, false));
    }
}

public partial class InGameRootViewModel {
    
    public InGameRootViewModel(uFrame.Kernel.IEventAggregator aggregator) : 
            base(aggregator) {
    }
}

public partial class BlueBirdAnimalViewModelBase : AnimalViewModel {
    
    public BlueBirdAnimalViewModelBase(uFrame.Kernel.IEventAggregator aggregator) : 
            base(aggregator) {
    }
    
    public override void Bind() {
        base.Bind();
    }
    
    public override void Read(ISerializerStream stream) {
        base.Read(stream);
    }
    
    public override void Write(ISerializerStream stream) {
        base.Write(stream);
    }
    
    protected override void FillCommands(System.Collections.Generic.List<uFrame.MVVM.ViewModelCommandInfo> list) {
        base.FillCommands(list);
    }
    
    protected override void FillProperties(System.Collections.Generic.List<uFrame.MVVM.ViewModelPropertyInfo> list) {
        base.FillProperties(list);
    }
}

public partial class BlueBirdAnimalViewModel {
    
    public BlueBirdAnimalViewModel(uFrame.Kernel.IEventAggregator aggregator) : 
            base(aggregator) {
    }
}

public partial class CoffeeCowAnimalViewModelBase : AnimalViewModel {
    
    public CoffeeCowAnimalViewModelBase(uFrame.Kernel.IEventAggregator aggregator) : 
            base(aggregator) {
    }
    
    public override void Bind() {
        base.Bind();
    }
    
    public override void Read(ISerializerStream stream) {
        base.Read(stream);
    }
    
    public override void Write(ISerializerStream stream) {
        base.Write(stream);
    }
    
    protected override void FillCommands(System.Collections.Generic.List<uFrame.MVVM.ViewModelCommandInfo> list) {
        base.FillCommands(list);
    }
    
    protected override void FillProperties(System.Collections.Generic.List<uFrame.MVVM.ViewModelPropertyInfo> list) {
        base.FillProperties(list);
    }
}

public partial class CoffeeCowAnimalViewModel {
    
    public CoffeeCowAnimalViewModel(uFrame.Kernel.IEventAggregator aggregator) : 
            base(aggregator) {
    }
}

public partial class GreenFrogAnimalViewModelBase : AnimalViewModel {
    
    public GreenFrogAnimalViewModelBase(uFrame.Kernel.IEventAggregator aggregator) : 
            base(aggregator) {
    }
    
    public override void Bind() {
        base.Bind();
    }
    
    public override void Read(ISerializerStream stream) {
        base.Read(stream);
    }
    
    public override void Write(ISerializerStream stream) {
        base.Write(stream);
    }
    
    protected override void FillCommands(System.Collections.Generic.List<uFrame.MVVM.ViewModelCommandInfo> list) {
        base.FillCommands(list);
    }
    
    protected override void FillProperties(System.Collections.Generic.List<uFrame.MVVM.ViewModelPropertyInfo> list) {
        base.FillProperties(list);
    }
}

public partial class GreenFrogAnimalViewModel {
    
    public GreenFrogAnimalViewModel(uFrame.Kernel.IEventAggregator aggregator) : 
            base(aggregator) {
    }
}
