// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using uFrame.Kernel;
using uFrame.MVVM;
using uFrame.MVVM.Bindings;
using uFrame.Serialization;


public class InGameRootViewHelperBase : uFrame.MVVM.ViewComponent {
    
    public virtual InGameRootViewModel InGameRoot {
        get {
            return (InGameRootViewModel)this.View.ViewModelObject;
        }
    }
    
    public virtual void ExecuteCreateAndDrop() {
        InGameRoot.CreateAndDrop.OnNext(new CreateAndDropCommand() { Sender = InGameRoot });
    }
    
    public virtual void ExecuteInitAllAnimal() {
        InGameRoot.InitAllAnimal.OnNext(new InitAllAnimalCommand() { Sender = InGameRoot });
    }
    
    public virtual void ExecuteTestCommand() {
        InGameRoot.TestCommand.OnNext(new TestCommandCommand() { Sender = InGameRoot });
    }
    
    public virtual void ExecuteCalcAnimalsCount() {
        InGameRoot.CalcAnimalsCount.OnNext(new CalcAnimalsCountCommand() { Sender = InGameRoot });
    }
    
    public virtual void ExecuteCreateAnimal(AnimalProp arg) {
        InGameRoot.CreateAnimal.OnNext(new CreateAnimalCommand() { Sender = InGameRoot, Argument = arg });
    }
    
    public virtual void ExecuteRemoveAnimal(AnimalProp arg) {
        InGameRoot.RemoveAnimal.OnNext(new RemoveAnimalCommand() { Sender = InGameRoot, Argument = arg });
    }
    
    public virtual void ExecuteRefreshSameCount(AnimalViewModel arg) {
        InGameRoot.RefreshSameCount.OnNext(new RefreshSameCountCommand() { Sender = InGameRoot, Argument = arg });
    }
    
    public virtual void ExecuteCreateAnimal(CreateAnimalCommand command) {
        command.Sender = InGameRoot;
        InGameRoot.CreateAnimal.OnNext(command);
    }
    
    public virtual void ExecuteRemoveAnimal(RemoveAnimalCommand command) {
        command.Sender = InGameRoot;
        InGameRoot.RemoveAnimal.OnNext(command);
    }
    
    public virtual void ExecuteCreateAndDrop(CreateAndDropCommand command) {
        command.Sender = InGameRoot;
        InGameRoot.CreateAndDrop.OnNext(command);
    }
    
    public virtual void ExecuteInitAllAnimal(InitAllAnimalCommand command) {
        command.Sender = InGameRoot;
        InGameRoot.InitAllAnimal.OnNext(command);
    }
    
    public virtual void ExecuteTestCommand(TestCommandCommand command) {
        command.Sender = InGameRoot;
        InGameRoot.TestCommand.OnNext(command);
    }
    
    public virtual void ExecuteRefreshSameCount(RefreshSameCountCommand command) {
        command.Sender = InGameRoot;
        InGameRoot.RefreshSameCount.OnNext(command);
    }
    
    public virtual void ExecuteCalcAnimalsCount(CalcAnimalsCountCommand command) {
        command.Sender = InGameRoot;
        InGameRoot.CalcAnimalsCount.OnNext(command);
    }
}
